In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction: ", hy_val)

Instructions for updating:
non-resource variables are not supported in the long term
0 Cost:  25958.348 
Prediction:  [12.284064 10.286286 12.462935 12.63334   7.633649]
10 Cost:  6.9827833 
Prediction:  [154.78128 181.57617 181.22798 196.41533 138.28848]
20 Cost:  6.709572 
Prediction:  [155.20248 182.10126 181.73555 196.96918 138.69276]
30 Cost:  6.6740975 
Prediction:  [155.19383 182.10965 181.73404 196.96861 138.70293]
40 Cost:  6.6388597 
Prediction:  [155.1839  182.11644 181.73102 196.9664  138.71187]
50 Cost:  6.6038084 
Prediction:  [155.17403 182.12323 181.72798 196.9642  138.7208 ]
60 Cost:  6.568923 
Prediction:  [155.16415 182.12999 181.72495 196.96199 138.72969]
70 Cost:  6.534228 
Prediction:  [155.15431 182.13675 181.72195 196.9598  138.73857]
80 Cost:  6.4997544 
Prediction:  [155.1445  182.14348 181.71895 196.95761 138.7474 ]
90 Cost:  6.4654417 
Prediction:  [155.1347  182.15018 181.71594 196.95541 138.75623]
100 Cost:  6.4313164 
Prediction:  [155.12495 182.15688 181

1230 Cost:  3.5557034 
Prediction:  [154.17636 182.80739 181.42256 196.741   139.62057]
1240 Cost:  3.5372841 
Prediction:  [154.16919 182.81232 181.42036 196.73941 139.62704]
1250 Cost:  3.519014 
Prediction:  [154.16206 182.81721 181.41818 196.73781 139.63348]
1260 Cost:  3.5008209 
Prediction:  [154.15494 182.8221  181.416   196.7362  139.63991]
1270 Cost:  3.4827087 
Prediction:  [154.14783 182.82697 181.41382 196.73462 139.64633]
1280 Cost:  3.4647098 
Prediction:  [154.14073 182.83183 181.41165 196.73303 139.65271]
1290 Cost:  3.4468122 
Prediction:  [154.13367 182.83667 181.40948 196.73145 139.65909]
1300 Cost:  3.4289842 
Prediction:  [154.12662 182.84152 181.40735 196.72987 139.66547]
1310 Cost:  3.4112828 
Prediction:  [154.1196  182.84634 181.40518 196.7283  139.6718 ]
1320 Cost:  3.393678 
Prediction:  [154.11258 182.85114 181.40303 196.72673 139.67812]
1330 Cost:  3.3761678 
Prediction:  [154.10559 182.85593 181.40091 196.72517 139.68443]
1340 Cost:  3.3587067 
Prediction:

In [2]:
#multi-variables linear regression using matrix

x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "cost: ", cost_val, "\nPrediction:\n", hy_val)

0 cost:  130406.21 
Prediction:
 [[-167.23985]
 [-201.6079 ]
 [-198.29228]
 [-216.90327]
 [-153.0546 ]]
10 cost:  2.5452323 
Prediction:
 [[152.20518]
 [182.34923]
 [180.02306]
 [195.07317]
 [139.80959]]
20 cost:  1.3449984 
Prediction:
 [[153.16747]
 [183.51387]
 [181.1664 ]
 [196.31874]
 [140.69948]]
30 cost:  1.3386065 
Prediction:
 [[153.16615]
 [183.52028]
 [181.16856]
 [196.32161]
 [140.70595]]
40 cost:  1.3322376 
Prediction:
 [[153.16193]
 [183.52318]
 [181.16725]
 [196.3207 ]
 [140.70973]]
50 cost:  1.3259108 
Prediction:
 [[153.1577 ]
 [183.5261 ]
 [181.16597]
 [196.31981]
 [140.71349]]
60 cost:  1.3196145 
Prediction:
 [[153.1535 ]
 [183.52898]
 [181.16467]
 [196.3189 ]
 [140.71725]]
70 cost:  1.3133686 
Prediction:
 [[153.1493 ]
 [183.53185]
 [181.16339]
 [196.318  ]
 [140.721  ]]
80 cost:  1.3071327 
Prediction:
 [[153.14511]
 [183.53471]
 [181.1621 ]
 [196.3171 ]
 [140.72473]]
90 cost:  1.3009535 
Prediction:
 [[153.14095]
 [183.53757]
 [181.16081]
 [196.31621]
 [140.7284

830 cost:  0.9246734 
Prediction:
 [[152.86134]
 [183.729  ]
 [181.07483]
 [196.25635]
 [140.97772]]
840 cost:  0.9205531 
Prediction:
 [[152.85794]
 [183.73132]
 [181.07376]
 [196.25563]
 [140.98076]]
850 cost:  0.9164523 
Prediction:
 [[152.85454]
 [183.73366]
 [181.07272]
 [196.25488]
 [140.98378]]
860 cost:  0.9123802 
Prediction:
 [[152.85115]
 [183.73598]
 [181.07169]
 [196.25418]
 [140.9868 ]]
870 cost:  0.90831107 
Prediction:
 [[152.84776]
 [183.7383 ]
 [181.07063]
 [196.25346]
 [140.98982]]
880 cost:  0.9042819 
Prediction:
 [[152.84439]
 [183.74062]
 [181.06961]
 [196.25273]
 [140.99281]]
890 cost:  0.90026695 
Prediction:
 [[152.84103]
 [183.74292]
 [181.06857]
 [196.25203]
 [140.99582]]
900 cost:  0.89628124 
Prediction:
 [[152.83768]
 [183.74521]
 [181.06754]
 [196.25131]
 [140.9988 ]]
910 cost:  0.8923133 
Prediction:
 [[152.83434]
 [183.7475 ]
 [181.06651]
 [196.25061]
 [141.00179]]
920 cost:  0.8883613 
Prediction:
 [[152.831  ]
 [183.74977]
 [181.06546]
 [196.2499 ]
 

1790 cost:  0.6152495 
Prediction:
 [[152.57266]
 [183.92659]
 [180.98595]
 [196.19508]
 [141.23453]]
1800 cost:  0.6127973 
Prediction:
 [[152.57004]
 [183.92839]
 [180.98514]
 [196.19453]
 [141.23688]]
1810 cost:  0.6103598 
Prediction:
 [[152.56741]
 [183.93019]
 [180.98433]
 [196.19397]
 [141.2392 ]]
1820 cost:  0.60793006 
Prediction:
 [[152.56479]
 [183.93199]
 [180.98352]
 [196.19342]
 [141.24152]]
1830 cost:  0.6055182 
Prediction:
 [[152.56218]
 [183.93378]
 [180.98273]
 [196.19287]
 [141.24385]]
1840 cost:  0.60313207 
Prediction:
 [[152.55959]
 [183.93555]
 [180.98193]
 [196.19232]
 [141.24615]]
1850 cost:  0.60073054 
Prediction:
 [[152.55698]
 [183.93733]
 [180.98111]
 [196.19177]
 [141.24846]]
1860 cost:  0.5983613 
Prediction:
 [[152.5544 ]
 [183.93912]
 [180.98033]
 [196.19124]
 [141.25076]]
1870 cost:  0.59599835 
Prediction:
 [[152.5518 ]
 [183.94087]
 [180.97952]
 [196.19067]
 [141.25305]]
1880 cost:  0.59365493 
Prediction:
 [[152.54924]
 [183.94264]
 [180.97873]
 [